import type { AutomationCopy } from "./Automations";

/** Complete English copy for the scheduled tasks view. */
export const AUTOMATION_COPY_EN: AutomationCopy = {
  title: "Scheduled tasks",
  subtitle: "Manage schedules, review their status, and see what needs attention and how each run went.",
  navLabel: "Scheduled task views",
  allTasks: "All schedules",
  attention: "Needs attention",
  paused: "Paused",
  runs: "Run history",
  newTask: "Create scheduled task",
  manageTasks: "Manage schedules",
  searchPlaceholder: "Search schedules, descriptions, or workspaces",
  clearSearch: "Clear search",
  taskCount: "Total schedules",
  attentionCount: "Needs attention",
  upcoming: "Up next",
  task: "Scheduled task",
  schedule: "Schedule",
  lastRun: "Last run",
  lastSkipped: "Last skipped",
  nextRun: "Next run",
  nextRunDeferred: "Calculating",
  neverRun: "Not run yet",
  noNextRun: "No upcoming run",
  workspace: "Workspace",
  delivery: "Send results to",
  timezone: "Time zone",
  runNow: "Run now",
  edit: "Edit",
  pause: "Pause",
  resume: "Resume",
  duplicate: "Duplicate",
  delete: "Delete",
  moreActions: "More schedule actions",
  openDetails: "Open schedule details",
  backToTasks: "Back to schedules",
  taskDetails: "Schedule details",
  taskInstructions: "Instructions",
  recentRuns: "Recent runs",
  openReplay: "View run",
  noRuns: "There are no runs yet. Results will appear here after a scheduled task runs.",
  noTasksTitle: "No scheduled tasks yet",
  noTasksBody: "Tell Hara what to do and when to do it. You can refine the settings later.",
  noFilteredTasksTitle: "No matching schedules",
  noFilteredTasksBody: "Clear the search or choose a different filter.",
  schedulerReady: "Scheduler is healthy",
  schedulerReadyBody: "Hara will run enabled scheduled tasks on this computer.",
  schedulerUnknown: "Checking the scheduler",
  schedulerUnknownBody: "Schedules are saved. Current health will appear when the service connects.",
  schedulerOffline: "Scheduler needs attention",
  schedulerOfflineBody: "Scheduled tasks will not trigger on time until the local scheduler is repaired.",
  schedulerMissing: "Scheduler installation required",
  schedulerMissingBody: "Install it once so scheduled tasks run even while Desktop is closed.",
  schedulerUnsupported: "Background scheduling is not available on this system",
  schedulerUnsupportedBody: "You can save, edit, and run scheduled tasks now, but this system cannot trigger them on schedule while Hara is closed yet.",
  installScheduler: "Install scheduler",
  lastChecked: "Last checked",
  statusScheduled: "Awaiting first run",
  statusActive: "On schedule",
  statusRunning: "Running",
  statusPaused: "Paused",
  statusAttention: "Needs attention",
  statusCompleted: "Completed",
  statusManual: "Manual run only",
  statusOffline: "Scheduler offline",
  statusScheduledHelp: "The schedule is ready and will run at its next scheduled time.",
  statusActiveHelp: "The schedule is enabled and its latest run completed normally.",
  statusRunningHelp: "Hara is running this scheduled task and will update the result when it finishes.",
  statusPausedHelp: "The schedule remains saved but will not run automatically.",
  statusAttentionHelp: "The latest run failed, timed out, or a due run could not start because a delivery prerequisite was unavailable.",
  statusCompletedHelp: "This one-time schedule has completed its run.",
  statusManualHelp: "Background scheduling is not available on this system yet. You can still save, edit, and run this scheduled task now.",
  statusOfflineHelp: "The schedule is enabled, but the local scheduler is currently unavailable.",
  resultOk: "Succeeded",
  resultError: "Failed",
  resultRunning: "Running",
  resultTimedOut: "Timed out",
  resultSkipped: "Not started",
  resultUnknown: "No result",
  skipDeliveryConfigurationRequired: "Delivery is not configured",
  skipDeliveryBlocked: "Delivery is blocked",
  skipDeliveryDeadLetter: "Delivery has stopped",
  skipUnknown: "Scheduled run was skipped",
  createdDescriptionPrint: "Send instructions to Hara on schedule and retain each answer.",
  createdDescriptionOrg: "Process an Org workflow on schedule and retain every result.",
  createdDescriptionCommand: "Run a command in the selected workspace and record its output and errors.",
  deliveryLocal: "Saved in Hara only",
  deliveryWebhook: "Webhook (address hidden)",
  deliveryExternal: "External notification",
  deliveryPending: "Pending delivery",
  deliveryRetrying: "Retrying",
  deliveryBlocked: "Delivery blocked; check credentials",
  deliveryDeadLetter: "Delivery stopped; check target or authorization",
  errorLabel: "Error",
  close: "Close",
  cancel: "Cancel",
  back: "Back",
  continue: "Continue",
  save: "Save changes",
  create: "Create scheduled task",
  saving: "Saving…",
  createTitle: "Create scheduled task",
  editTitle: "Edit scheduled task",
  duplicateTitle: "Duplicate scheduled task",
  createIntro: "Describe the work first, then choose when it runs. Advanced settings are optional.",
  stepTask: "Work",
  stepSchedule: "Schedule",
  stepReview: "Review",
  taskName: "Schedule name",
  taskNamePlaceholder: "For example: Summarize project progress daily",
  whatShouldRun: "What should Hara do?",
  taskPromptPlaceholder: "For example: Read today's commits and prepare a concise project update.",
  workingDirectory: "Where should it work?",
  workingDirectoryPlaceholder: "Optional, for example /Users/me/project",
  workingDirectoryHelp: "Enter a path directly or choose a folder from this computer.",
  browseDirectory: "Choose folder",
  directoryPickerFailed: "The folder picker could not open. Try again or enter the path directly.",
  executionMode: "Execution mode",
  modePrint: "Hara instruction",
  modePrintHelp: "Ask Hara to summarize, inspect, or organize information.",
  modeOrg: "Org workflow",
  modeOrgHelp: "Process a fixed workflow or task defined by your organization.",
  modeCommand: "Local command",
  modeCommandHelp: "Run an existing script directly. Only use commands you trust.",
  whenShouldRun: "When should it run?",
  cadenceOnce: "Once",
  cadenceInterval: "At an interval",
  cadenceDaily: "Daily",
  cadenceWeekly: "Weekly",
  cadenceCustom: "Custom",
  dateAndTime: "Date and time",
  every: "Every",
  minutes: "minutes",
  hours: "hours",
  days: "days",
  atTime: "Run time",
  chooseDays: "Choose days",
  customSchedule: "Cron expression",
  customScheduleHelp: "Advanced. Example: 0 9 * * 1-5 means weekdays at 09:00.",
  timezoneHelp: "All scheduled times use this time zone.",
  advancedOptions: "Advanced options",
  deliveryMode: "Notification policy",
  deliveryTarget: "Notification target",
  deliveryTargetPlaceholder: "For example feishu:chat-id or webhook:https://…",
  deliveryTargetHelp: "The target is stored locally and its full value is hidden after saving.",
  deliveryOff: "Save results only",
  deliveryAlways: "Notify after every run",
  deliveryOnOutput: "Notify when there is output",
  deliveryOnError: "Notify only on failure",
  alertAfter: "Consecutive failure threshold",
  alertAfterHelp: "Mark the schedule as needing attention after this many consecutive failures.",
  reviewTitle: "Review scheduled task settings",
  reviewHelp: "You can edit, pause, run, or duplicate this scheduled task after saving.",
  schedulePreview: "Schedule preview",
  taskRequired: "Describe the work Hara should perform.",
  nameRequired: "Give the schedule a recognizable name.",
  scheduleRequired: "Choose a valid future schedule.",
  deleteTitle: "Delete this scheduled task?",
  deleteBody: "The schedule will be removed and will no longer run automatically.",
  deleteWarning: "Existing run history may remain. This action cannot be undone.",
  deleteConfirm: "Delete scheduled task",
  deleting: "Deleting…",
  operationFailed: "The operation failed. Please try again.",
  runningAction: "Working…",
  loading: "Loading scheduled tasks…",
  unknown: "Unknown",
  today: "Today",
  tomorrow: "Tomorrow",
};
