import type { AutomationCopy } from "./Automations";

/** Complete English copy so changing Desktop language never leaves the task console half translated. */
export const AUTOMATION_COPY_EN: AutomationCopy = {
  title: "Automations",
  subtitle: "Let Hara run recurring work at the right time and keep every result here.",
  navLabel: "Automation views",
  allTasks: "All tasks",
  attention: "Needs attention",
  paused: "Paused",
  runs: "Run history",
  newTask: "New automation",
  searchPlaceholder: "Search tasks, descriptions, or workspaces",
  clearSearch: "Clear search",
  taskCount: "Total tasks",
  attentionCount: "Needs attention",
  upcoming: "Up next",
  task: "Task",
  schedule: "Schedule",
  lastRun: "Last run",
  nextRun: "Next run",
  neverRun: "Not run yet",
  noNextRun: "No upcoming run",
  workspace: "Workspace",
  delivery: "Send results to",
  timezone: "Time zone",
  runNow: "Run now",
  edit: "Edit",
  pause: "Pause",
  resume: "Resume",
  duplicate: "Duplicate",
  delete: "Delete",
  moreActions: "More task actions",
  openDetails: "Open task details",
  backToTasks: "Back to tasks",
  taskDetails: "Task details",
  taskInstructions: "Instructions",
  recentRuns: "Recent runs",
  openReplay: "View run",
  noRuns: "There are no runs yet. Results will appear here after a task runs.",
  noTasksTitle: "No automations yet",
  noTasksBody: "Tell Hara what to do and when to do it. You can refine the settings later.",
  noFilteredTasksTitle: "No matching tasks",
  noFilteredTasksBody: "Clear the search or choose a different filter.",
  schedulerReady: "Scheduler is healthy",
  schedulerReadyBody: "Hara will trigger enabled tasks on this computer.",
  schedulerUnknown: "Checking the scheduler",
  schedulerUnknownBody: "Tasks are saved. Current health will appear when the service connects.",
  schedulerOffline: "Scheduler needs attention",
  schedulerOfflineBody: "Tasks will not trigger on time until the local scheduler is repaired.",
  schedulerMissing: "Scheduler installation required",
  schedulerMissingBody: "Install it once so tasks run even while Desktop is closed.",
  installScheduler: "Install scheduler",
  lastChecked: "Last checked",
  statusScheduled: "Awaiting first run",
  statusActive: "On schedule",
  statusRunning: "Running",
  statusPaused: "Paused",
  statusAttention: "Needs attention",
  statusCompleted: "Completed",
  statusOffline: "Scheduler offline",
  statusScheduledHelp: "The task is ready and will run at its next scheduled time.",
  statusActiveHelp: "The task is enabled and its latest run completed normally.",
  statusRunningHelp: "Hara is running this task and will update the result when it finishes.",
  statusPausedHelp: "The task remains saved but will not run automatically.",
  statusAttentionHelp: "The latest run failed or timed out. Review the error before retrying.",
  statusCompletedHelp: "This one-time task has completed its scheduled run.",
  statusOfflineHelp: "The task is enabled, but the local scheduler is currently unavailable.",
  resultOk: "Succeeded",
  resultError: "Failed",
  resultRunning: "Running",
  resultTimedOut: "Timed out",
  resultUnknown: "No result",
  createdDescriptionPrint: "Send instructions to Hara on schedule and retain each answer.",
  createdDescriptionOrg: "Process an Org workflow on schedule and retain every result.",
  createdDescriptionCommand: "Run a command in the selected workspace and record its output and errors.",
  deliveryLocal: "Saved in Hara only",
  deliveryWebhook: "Webhook (address hidden)",
  deliveryExternal: "External notification",
  errorLabel: "Error",
  close: "Close",
  cancel: "Cancel",
  back: "Back",
  continue: "Continue",
  save: "Save changes",
  create: "Create task",
  saving: "Saving…",
  createTitle: "New automation",
  editTitle: "Edit automation",
  duplicateTitle: "Duplicate automation",
  createIntro: "Describe the work first, then choose when it runs. Advanced settings are optional.",
  stepTask: "Work",
  stepSchedule: "Schedule",
  stepReview: "Review",
  taskName: "Task name",
  taskNamePlaceholder: "For example: Summarize project progress daily",
  whatShouldRun: "What should Hara do?",
  taskPromptPlaceholder: "For example: Read today's commits and prepare a concise project update.",
  workingDirectory: "Where should it work?",
  workingDirectoryPlaceholder: "Optional, for example /Users/me/project",
  executionMode: "Execution mode",
  modePrint: "Hara instruction",
  modePrintHelp: "Ask Hara to summarize, inspect, or organize information.",
  modeOrg: "Org workflow",
  modeOrgHelp: "Process a fixed workflow or task defined by your organization.",
  modeCommand: "Local command",
  modeCommandHelp: "Run an existing script directly. Only use commands you trust.",
  whenShouldRun: "When should it run?",
  cadenceOnce: "Once",
  cadenceInterval: "At an interval",
  cadenceDaily: "Daily",
  cadenceWeekly: "Weekly",
  cadenceCustom: "Custom",
  dateAndTime: "Date and time",
  every: "Every",
  minutes: "minutes",
  hours: "hours",
  days: "days",
  atTime: "Run time",
  chooseDays: "Choose days",
  customSchedule: "Cron expression",
  customScheduleHelp: "Advanced. Example: 0 9 * * 1-5 means weekdays at 09:00.",
  timezoneHelp: "All scheduled times use this time zone.",
  advancedOptions: "Advanced options",
  deliveryMode: "Notification policy",
  deliveryTarget: "Notification target",
  deliveryTargetPlaceholder: "For example feishu:chat-id or webhook:https://…",
  deliveryTargetHelp: "The target is stored locally and its full value is hidden after saving.",
  deliveryOff: "Save results only",
  deliveryAlways: "Notify after every run",
  deliveryOnOutput: "Notify when there is output",
  deliveryOnError: "Notify only on failure",
  alertAfter: "Consecutive failure threshold",
  alertAfterHelp: "Mark the task as needing attention after this many consecutive failures.",
  reviewTitle: "Review task settings",
  reviewHelp: "You can edit, pause, run, or duplicate this task after saving.",
  schedulePreview: "Schedule preview",
  taskRequired: "Describe the work Hara should perform.",
  nameRequired: "Give the task a recognizable name.",
  scheduleRequired: "Choose a valid future schedule.",
  deleteTitle: "Delete this automation?",
  deleteBody: "The task will be removed and will no longer run automatically.",
  deleteWarning: "Existing run history may remain. This action cannot be undone.",
  deleteConfirm: "Delete task",
  deleting: "Deleting…",
  operationFailed: "The operation failed. Please try again.",
  runningAction: "Working…",
  loading: "Loading automations…",
  unknown: "Unknown",
  today: "Today",
  tomorrow: "Tomorrow",
};
